version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: "forestindex"
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    restart: "always"
    volumes:
      - ./src:/api/src
