# named ~/docker-compose.yml in production
version: '2'
services:

  api:
    image: 081027247578.dkr.ecr.us-east-1.amazonaws.com/api:latest
    container_name: api
    environment:
     - NODE_ENV=production
    ports:
     - '8080:8080'
    restart: always
