version: '2'
services:

  api:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/dev.Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    restart: "always"
    volumes:
      - ./src:/api/src
      - ./ssl:/api/ssl
