version: '2'
services:

  api:
    image: "081027247578.dkr.ecr.us-east-1.amazonaws.com/bluecactus/forest-index:latest"
    container_name: "forestindex"
    environment:
     - NODE_ENV=production
    ports:
     - "8080:8080"
    restart: "always"
