version: '2'
services:

  api:
    image: "081027247578.dkr.ecr.us-east-1.amazonaws.com/api:latest"
    container_name: "api"
    environment:
     - NODE_ENV=production
    ports:
     - "443:443"
    restart: "always"
    volumes:
      - /ssl/key
      - /ssl/cert.pem
