version: '2'
services:

  api:
    image: "081027247578.dkr.ecr.us-east-1.amazonaws.com/bluecactus/forest-index:latest"
    container_name: "forestindex"
    environment:
     - NODE_ENV=production
    ports:
     - "8080:8080"
    restart: "always"

  nginx:
    image: "081027247578.dkr.ecr.us-east-1.amazonaws.com/nginx-bravo:latest"
    container_name: "nginx"
    ports:
     - "443:443"
    restart: "always"
    volumes:
     - "./~/ssl:/etc/letsencrypt/live/indexapi.forestindex.com"
    environment:
     - LINK_CONTAINER_NAME=forestindex
     - PROXY_PORT=8080
    links:
     - api