defaults: &defaults
  working_directory: ~/forestindexapi
  docker:
    # custom docker image to run commands in. Thanks Rhinogram, LLC
    - image: rhinogram/node-awscli:latest


version: 2
jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set AWS Keys
          command: |
            mkdir ~/.aws && touch ~/.aws/credentials
            echo -e "\n[default]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY\n" >> ~/.aws/credentials
      - run:
          name: Get Config File
          command: aws s3 cp s3://bluecactus-devops/forestindex/configs/config.js src/
      - run:
          name: Build Image
          command: yarn docker:build
      - run: 
          name: Cache Image
          command: |
            mkdir tmp_docker_cache
            docker save -o tmp_docker_cache/forestindexapi.tar forest-index
      - persist_to_workspace:
          root: tmp_docker_cache
          paths:
            - forestindexapi.tar
  
  deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/forestindexapi/tmp_docker_cache
      - run:
          name: Set AWS Keys
          command: |
            # Explicitly set keys on per job
            mkdir ~/.aws && touch ~/.aws/credentials
            echo -e "\n[default]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY\n" >> ~/.aws/credentials
      - run:
          name: Load Cached Docker Image
          command: docker load -i tmp_docker_cache/forestindexapi.tar
      - run:
          name: Push Docker Image
          command: |
            $(aws ecr get-login --no-include-email --region $AWS_REGION)
            LATEST=$ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/bluecactus/forest-index:latest
            docker tag forest-index $LATEST
            docker push $LATEST
      - run: yarn
      - run:
          name: Deploy
          command: node deploy.js


workflows:
  version: 2

  general:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master

  deploy_master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
